services:
  jenkins:
    container_name: jenkins
    restart: on-failure
    build: .
    depends_on:
      - dind
    privileged: true
    ports:
      - "${HOST_PORT}:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    networks:
      - jenkins
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
  dind:
    image: docker:dind
    container_name: dind
    privileged: true
    ports:
      - "2376:2376"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - jenkins-docker-certs:/certs/client
      - dind:/var/lib/docker
    networks:
      jenkins:
        aliases:
          - docker
    environment:
      - DOCKER_TLS_CERTDIR=/certs
networks:
  jenkins:
volumes:
  jenkins-docker-certs:
  dind:
